# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_question_pos_tagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pos_tagging',
        ),
        migrations.AddField(
            model_name='decomposedquestion',
            name='pos_tagging',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
