# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_answercandidate_answertriple'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertriple',
            name='relation',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
